### ISSUE TITLE
You can't not watch this

### ISSUE THREAD

**Issue by garthk** [substack/catw#3]
Despite the `README`, dumping `opts` in `bin/cmd.js:76` shows `watch` is `true` for:

* `npm run html` with `scripts` `html` set to `"catw static/index.html > dist/index.html"`
* `node_modules/.bin/catw static/index.html -o -`
* `node_modules/.bin/catw static/index.html`
* `node node_modules/catw/bin/cmd.js static/index.html -o -`
* `node node_modules/catw/bin/cmd.js static/index.html`

My `npm version` output in `node_modules/catw` is:

```js
{ catw: '1.0.0',
  npm: '2.10.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.4',
  openssl: '1.0.1m',
  uv: '1.5.0',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```

**Comment by substack** [comment]
Fixed in 1.0.1: https://github.com/substack/catw/commit/b2d484c91a1fa84cb8f7c2d5ee909bc4fbe1fb77
